/**
 * Badge-Count-Notification Component Index
 * 
 * Stemma System naming: [Family]-[Type]-[Variant] = Badge-Count-Notification
 * Type: Semantic Variant (inherits from Badge-Count-Base)
 * 
 * Badge-Count-Notification is a semantic variant that extends Badge-Count-Base
 * with notification-specific styling and live region announcements for screen
 * readers. It uses predefined notification color tokens and automatically
 * announces count changes to assistive technologies.
 * 
 * Key Characteristics:
 * - Inherits all Badge-Count-Base behavior (count display, max truncation, showZero)
 * - Fixed notification colors (pink400 background, white100 text)
 * - Live region announcements for accessibility
 * - Pluralized announcement text ("1 notification", "5 notifications")
 * - Optional announceChanges prop (default: true)
 * 
 * COLOR TOKENS (Spec 058):
 * Badge notification color tokens are defined in this component directory following
 * the Rosetta System architecture which mandates component tokens live at
 * src/components/[ComponentName]/tokens.ts.
 * 
 * @see ./README.md for complete documentation
 * @see ./tokens.ts for component color token definitions
 * @see .kiro/specs/044-badge-base for design specification
 * @see .kiro/specs/058-component-token-architecture-cleanup for color token migration
 * @see .kiro/specs/034-component-architecture-system for Stemma System details
 */

// Types
export { 
  BadgeCountNotificationProps,
  BadgeCountSize,
  BADGE_COUNT_NOTIFICATION_DEFAULTS,
} from './types';

// Component Tokens (Spec 058 - canonical location per Rosetta System architecture)
export {
  BadgeNotificationColorTokens,
  BadgeNotificationColorTokenKey,
  getBadgeNotificationColorToken,
  BadgeNotificationTokenReferences,
} from './tokens';

// Web Platform Implementation
export { BadgeCountNotification } from './platforms/web/BadgeCountNotification.web';

// Platform implementations:
// - Web: BadgeCountNotification (Task 4.2) - complete
// - iOS: BadgeCountNotification (Task 4.3) - complete
// - Android: BadgeCountNotification (Task 4.4) - complete
//
// Platform Token Usage:
// - Web: Uses CSS custom properties (--color-badge-notification-background, --color-badge-notification-text)
//        generated by the token build pipeline from tokens.ts
// - iOS: Uses DesignTokens.colorBadgeNotificationBackground and DesignTokens.colorBadgeNotificationText
//        generated by the token build pipeline from tokens.ts
// - Android: Uses DesignTokens.color_badge_notification_background and DesignTokens.color_badge_notification_text
//            generated by the token build pipeline from tokens.ts
